config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),

    path("",include("planning.urls")),
]

planning/urls.py
from django.urls import path
from . import views

app_name    = "planning"
urlpatterns = [
    path('', views.index, name="index"),
    path('edit/<int:pk>/', views.edit, name="edit"),
]

planning/models.py
from django.db import models


STATUS  = [
            ("未選択","未選択"),
            ("承認"  ,"承認"),
            ("未承認","未承認"),
        ]


class Plan(models.Model):

    name        = models.CharField(verbose_name="企画名",max_length=50)

    staff       = models.CharField(verbose_name="担当の許可",choices=STATUS,max_length=3,default="未選択")
    manager     = models.CharField(verbose_name="課長の許可",choices=STATUS,max_length=3,default="未選択")
    director    = models.CharField(verbose_name="部長の許可",choices=STATUS,max_length=3,default="未選択")
    company     = models.CharField(verbose_name="部長の許可",choices=STATUS,max_length=3,default="未選択")

planning/forms.py
from django import forms

from .models import Plan


class PlanForm(forms.ModelForm):

    class Meta:
        model   = Plan
        fields  = ["name"]


class PlanEditStaffForm(forms.ModelForm):

    class Meta:
        model   = Plan
        fields  = ["staff"]

class PlanEditManagerForm(forms.ModelForm):

    class Meta:
        model   = Plan
        fields  = ["manager"]

class PlanEditDirectorForm(forms.ModelForm):

    class Meta:
        model   = Plan
        fields  = ["director"]

class PlanEditCompanyForm(forms.ModelForm):

    class Meta:
        model   = Plan
        fields  = ["company"]

planning/views.py
from django.shortcuts import render,redirect

from django.views import View
from .models import Plan

from .forms import PlanForm,PlanEditStaffForm,PlanEditManagerForm,PlanEditDirectorForm,PlanEditCompanyForm

class IndexView(View):

    def get(self, request, *args, **kwargs):

        plans   = Plan.objects.all()
        context = { "plans":plans }

        return render(request,"planning/index.html",context)

    def post(self, request, *args, **kwargs):

        form    = PlanForm(request.POST)

        if form.is_valid():
            print("保存")
            form.save()


        return redirect("planning:index")

index   = IndexView.as_view()



#TODO:ここでログインを済ませたユーザーのみ編集を受け入れる。

class EditView(View):

    def post(self, request, pk, *args, **kwargs):


        plan    = Plan.objects.filter(id=pk).first()

        form    = PlanEditStaffForm(request.POST,instance=plan)
        if form.is_valid():
            form.save()

        form    = PlanEditManagerForm(request.POST,instance=plan)
        if form.is_valid():
            form.save()
            
        form    = PlanEditDirectorForm(request.POST,instance=plan)
        if form.is_valid():
            form.save()

        form    = PlanEditCompanyForm(request.POST,instance=plan)
        if form.is_valid():
            form.save()


        return redirect("planning:index")

edit    = EditView.as_view()

templates/planning/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>企画承認システム</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>
    <h1 class="bg-primary text-white">企画承認システム</h1>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="text" name="name">
        <input type="submit" value="作成">
    </form>


    <div class="row mx-0">
        <div class="col">プラン名</div>
        <div class="col">担当</div>
        <div class="col">課長</div>
        <div class="col">部長</div>
        <div class="col">B社</div>
    </div>

    {% for plan in plans %}
    <div class="row mx-0">

        <div class="col">{{ plan.name }}</div>
        <div class="col">
            <form action="{% url 'planning:edit' plan.id %}" method="POST">
                {% csrf_token %}
                <select name="staff">
                    <option value="未選択"  {% if plan.staff == "未選択"%}selected{% endif %}>未選択</option>
                    <option value="承認"    {% if plan.staff == "承認"  %}selected{% endif %}>承認</option>
                    <option value="未承認"  {% if plan.staff == "未承認"%}selected{% endif %}>未承認</option>
                </select>
                <input type="submit" value="送信">
            </form>
        </div>

        <div class="col">
            <form action="{% url 'planning:edit' plan.id %}" method="POST">
                {% csrf_token %}
                <select name="manager">
                    <option value=""        {% if plan.manager == ""      %}selected{% endif %}>未選択</option>
                    <option value="承認"    {% if plan.manager == "承認"  %}selected{% endif %}>承認</option>
                    <option value="未承認"  {% if plan.manager == "未承認"%}selected{% endif %}>未承認</option>
                </select>
                <input type="submit" value="送信">
            </form>
        </div>

        <div class="col">
            <form action="{% url 'planning:edit' plan.id %}" method="POST">
                {% csrf_token %}
                <select name="director">
                    <option value=""        {% if plan.director == ""      %}selected{% endif %}>未選択</option>
                    <option value="承認"    {% if plan.director == "承認"  %}selected{% endif %}>承認</option>
                    <option value="未承認"  {% if plan.director == "未承認"%}selected{% endif %}>未承認</option>
                </select>
                <input type="submit" value="送信">
            </form>
        </div>

        <div class="col">
            <form action="{% url 'planning:edit' plan.id %}" method="POST">
                {% csrf_token %}
                <select name="company">
                    <option value=""        {% if plan.company == ""      %}selected{% endif %}>未選択</option>
                    <option value="承認"    {% if plan.company == "承認"  %}selected{% endif %}>承認</option>
                    <option value="未承認"  {% if plan.company == "未承認"%}selected{% endif %}>未承認</option>
                </select>
                <input type="submit" value="送信">
            </form>
        </div>
    
    </div>

    {% endfor %}



</body>
</html>